version: '3.7'

networks:
  netop1:

services:

  ca.netop1.com:
    image: hyperledger/fabric-ca
    container_name: ca.netop1.com
    ports:
    - 7054:7054
    environment:
    - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
    - FABRIC_CA_SERVER_PORT=7054
    - FABRIC_CA_SERVER_TLS_ENABLED=true
    - FABRIC_CA_SERVER_CSR_CN=ca.netop1.com
    - FABRIC_CA_SERVER_CSR_HOSTS=ca.netop1.com,localhost
    volumes:
    - ./ca-server:/etc/hyperledger/fabric-ca-server
    command: sh -c 'fabric-ca-server start -b caadmin:caadminpw --tls.enabled'
    networks:
    - netop1

  tlsca.netop1.com:
    image: hyperledger/fabric-ca
    container_name: tlsca.netop1.com
    ports:
    - 7055:7054
    environment:
    - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
    - FABRIC_CA_SERVER_PORT=7054
    - FABRIC_CA_SERVER_TLS_ENABLED=true
    - FABRIC_CA_SERVER_CSR_CN=tlsca.netop1.com
    - FABRIC_CA_SERVER_CSR_HOSTS=tlsca.netop1.com,localhost
    volumes:
    - ./tlsca-server:/etc/hyperledger/fabric-ca-server
    command: sh -c 'fabric-ca-server start -b tlsadmin:tlsadminpw --tls.enabled'
    networks:
    - netop1

  caclient.netop1.com:
    image: hyperledger/fabric-ca
    container_name: caclient.netop1.com
    environment:
    - SVC_DOMAIN=netop1.svc.cluster.local
    - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-client
    - FABRIC_CA_CLIENT_TLS_CERTFILES=/etc/hyperledger/fabric-ca-client/tls-cert.pem
    volumes:
    - ./ca-client:/etc/hyperledger/fabric-ca-client
    command: bash -c 'while true; do sleep 30; done'
    networks:
    - netop1
