version: '3.7'

services:
  tool:
    container_name: tool
    image: hyperledger/fabric-tools
    tty: true
    stdin_open: true
    environment:
      - ORG=netop1
      - SYS_CHANNEL=netop1-channel
      - TEST_CHANNEL=mychannel
      - ORDERER_TYPE=solo
      - FABRIC_CFG_PATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/config/artifacts
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      #- FABRIC_LOGGING_SPEC=DEBUG
      - FABRIC_LOGGING_SPEC=INFO
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash -c 'cd config/artifacts && ./gen-config-block.sh'
    volumes:
        - /var/run/:/host/var/run/
        - ./../:/opt/gopath/src/github.com/hyperledger/fabric/peer/config/
    networks:
    - netop1

networks:
  netop1:

