---
Organizations:

    - &peerorg1MSP
        Name: peerorg1MSP
        ID: peerorg1MSP
        MSPDir: /etc/hyperledger/tool/crypto/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('peerorg1MSP.admin', 'peerorg1MSP.peer', 'peerorg1MSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('peerorg1MSP.admin', 'peerorg1MSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('peerorg1MSP.admin')"

        AnchorPeers:
            - Host: peer-0.peer.peerorg1.svc.cluster.local
              Port: 7051

Capabilities:
    Channel: &ChannelCapabilities
        V1_4_3: true
        V1_3: false
        V1_1: false
    Orderer: &OrdererCapabilities
        V1_4_2: true
        V1_1: false
    Application: &ApplicationCapabilities
        V1_4_2: true
        V1_3: false
        V1_2: false
        V1_1: false

Application: &ApplicationDefaults
    Organizations:
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"

    Capabilities:
        <<: *ApplicationCapabilities

Channel: &ChannelDefaults
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
    Capabilities:
        <<: *ChannelCapabilities

Profiles:

    peerorg1Channel:
        Consortium: peerorg1Consortium
        <<: *ChannelDefaults
        Application:
            <<: *ApplicationDefaults
            Organizations:
                - *peerorg1MSP
            Capabilities:
                <<: *ApplicationCapabilities
