
kind: PersistentVolume
apiVersion: v1
# config data for cli
metadata:
  name: config-cli
  labels:
    app: cli
    org: netop1
spec:
  capacity:
    storage: 100Mi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /Users/yxu/work/hyperledger/fabric-operation/netop1.com/k8s/cli
    type: Directory
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: config-cli
  namespace: netop1
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  selector:
    matchLabels:
      app: cli
      org: netop1
---
apiVersion: v1
kind: Pod
metadata:
  name: cli
  namespace: netop1
spec:
  containers:
  - name: cli
    image: hyperledger/fabric-tools
    imagePullPolicy: Always
    command:
    - bash
    - -c
    - "while true; do sleep 30; done"
    env:
    - name: CORE_PEER_ADDRESS
      value: peer-0.peer.netop1.svc.cluster.local:7051
    - name: CORE_PEER_ID
      value: cli
    - name: CORE_PEER_LOCALMSPID
      value: netop1MSP
    - name: CORE_PEER_MSPCONFIGPATH
      value: /etc/hyperledger/cli/config/Admin@netop1.com/msp
    - name: CORE_PEER_TLS_CERT_FILE
      value: /etc/hyperledger/cli/config/peer-0.netop1.com/tls/server.crt
    - name: CORE_PEER_TLS_ENABLED
      value: "true"
    - name: CORE_PEER_TLS_KEY_FILE
      value: /etc/hyperledger/cli/config/peer-0.netop1.com/tls/server.key
    - name: CORE_PEER_TLS_ROOTCERT_FILE
      value: /etc/hyperledger/cli/config/peer-0.netop1.com/tls/ca.crt
    - name: CORE_VM_ENDPOINT
      value: unix:///host/var/run/docker.sock
    - name: FABRIC_LOGGING_SPEC
      value: DEBUG
    - name: GOPATH
      value: /opt/gopath
    - name: ORDERER_CA
      value: /etc/hyperledger/cli/config/orderer-0.netop1.com/msp/tlscacerts/tlsca.netop1.com-cert.pem
    - name: ORDERER_TYPE
      value: solo
    - name: ORDERER_URL
      value: orderer-0.orderer.netop1.svc.cluster.local:7050
    - name: ORG
      value: netop1
    - name: SYS_CHANNEL
      value: netop1-channel
    - name: TEST_CHANNEL
      value: mychannel
    workingDir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    volumeMounts:
    - mountPath: /host/var/run
      name: docker-sock
    - mountPath: /etc/hyperledger/cli/config
      name: config
  volumes:
  - name: docker-sock
    hostPath:
      path: /var/run
      type: Directory
  - name: config
    persistentVolumeClaim:
      claimName: config-cli
