version: '3.7'

services:
  tool:
    container_name: tool
    image: hyperledger/fabric-tools
    tty: true
    stdin_open: true
    environment:
      - FABRIC_CFG_PATH=/etc/hyperledger/tool
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=INFO
      - SYS_CHANNEL=netop1-channel
      - ORG=netop1
      - ORG_MSP=netop1MSP
      - ORDERER_TYPE=etcdraft
      - TEST_CHANNEL=mychannel
      - FABRIC_ORG=netop1.com
    working_dir: /etc/hyperledger/tool
    command: /bin/bash -c 'while true; do sleep 30; done'
    volumes:
        - /var/run/:/host/var/run/
        - /Users/yxu/work/hyperledger/fabric-operation/netop1.com/tool/:/etc/hyperledger/tool
    networks:
    - netop1

networks:
  netop1:

