version: '3.7'

services:
  tool:
    container_name: tool
    image: hyperledger/fabric-tools
    tty: true
    stdin_open: true
    environment:
      - FABRIC_CFG_PATH=/etc/hyperledger/tool
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=INFO
    working_dir: /etc/hyperledger/tool
    command: /bin/bash -c "
        configtxgen -profile etcdraftOrdererGenesis -channelID netop1-channel -outputBlock ./genesis.block
        && configtxgen -profile netop1Channel -outputCreateChannelTx ./channel.tx -channelID mychannel
        && configtxgen -profile netop1Channel -outputAnchorPeersUpdate ./anchors.tx -channelID mychannel -asOrg netop1MSP
      "
    volumes:
        - /var/run/:/host/var/run/
        - /Users/yxu/work/hyperledger/fabric-operation/netop1.com/tool/:/etc/hyperledger/tool
    networks:
    - netop1

networks:
  netop1:

