
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: peerorg1-ca-data-class
provisioner: kubernetes.io/no-provisioner
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
---
kind: PersistentVolume
apiVersion: v1
# create PV for ca-server
metadata:
  name: ca-server-peerorg1-pv
  labels:
    node: ca-server
    org: peerorg1
spec:
  capacity:
    storage: 100Mi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: peerorg1-ca-data-class
  hostPath:
    path: /Users/yxu/work/hyperledger/fabric-operation/peerorg1.com/canet/ca-server
    type: Directory
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ca-server-pvc
  namespace: peerorg1
spec:
  storageClassName: peerorg1-ca-data-class
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  selector:
    matchLabels:
      node: ca-server
      org: peerorg1
---
kind: PersistentVolume
apiVersion: v1
# create PV for tlsca-server
metadata:
  name: tlsca-server-peerorg1-pv
  labels:
    node: tlsca-server
    org: peerorg1
spec:
  capacity:
    storage: 100Mi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: peerorg1-ca-data-class
  hostPath:
    path: /Users/yxu/work/hyperledger/fabric-operation/peerorg1.com/canet/tlsca-server
    type: Directory
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: tlsca-server-pvc
  namespace: peerorg1
spec:
  storageClassName: peerorg1-ca-data-class
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  selector:
    matchLabels:
      node: tlsca-server
      org: peerorg1
---
kind: PersistentVolume
apiVersion: v1
# create PV for ca-client
metadata:
  name: ca-client-peerorg1-pv
  labels:
    node: ca-client
    org: peerorg1
spec:
  capacity:
    storage: 100Mi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: peerorg1-ca-data-class
  hostPath:
    path: /Users/yxu/work/hyperledger/fabric-operation/peerorg1.com
    type: Directory
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ca-client-pvc
  namespace: peerorg1
spec:
  storageClassName: peerorg1-ca-data-class
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  selector:
    matchLabels:
      node: ca-client
      org: peerorg1
