
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: cli-data-class
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: data-cli-pv
  labels:
    app: data-cli
    org: netop1
spec:
  capacity:
    storage: 100Mi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: cli-data-class
  hostPath:
    path: /Users/yxu/work/hyperledger/fabric-operation/netop1.com/cli
    type: Directory
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: data-cli-pvc
  namespace: netop1
spec:
  storageClassName: cli-data-class
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  selector:
    matchLabels:
      app: data-cli
      org: netop1
