
apiVersion: v1
kind: Pod
metadata:
  name: cli
  namespace: netop1
spec:
  containers:
  - name: cli
    image: hyperledger/fabric-tools
    imagePullPolicy: Always
    command:
    - bash
    - -c
    - "while true; do sleep 30; done"
    env:
    - name: CORE_PEER_ADDRESS
      value: peer-0.peer.netop1.svc.cluster.local:7051
    - name: CORE_PEER_ID
      value: cli
    - name: CORE_PEER_LOCALMSPID
      value: netop1MSP
    - name: CORE_PEER_MSPCONFIGPATH
      value: /etc/hyperledger/cli/crypto/Admin@netop1.com/msp
    - name: CORE_PEER_TLS_CERT_FILE
      value: /etc/hyperledger/cli/crypto/peer-0.netop1.com/tls/server.crt
    - name: CORE_PEER_TLS_ENABLED
      value: "true"
    - name: CORE_PEER_TLS_KEY_FILE
      value: /etc/hyperledger/cli/crypto/peer-0.netop1.com/tls/server.key
    - name: CORE_PEER_TLS_ROOTCERT_FILE
      value: /etc/hyperledger/cli/crypto/peer-0.netop1.com/tls/ca.crt
    - name: CORE_VM_ENDPOINT
      value: unix:///host/var/run/docker.sock
    - name: FABRIC_LOGGING_SPEC
      value: INFO
    - name: GOPATH
      value: /opt/gopath
    - name: ORDERER_CA
      value: /etc/hyperledger/cli/crypto/orderer-0.netop1.com/msp/tlscacerts/tlsca.netop1.com-cert.pem
    - name: ORDERER_TYPE
      value: etcdraft
    - name: ORDERER_URL
      value: orderer-0.orderer.netop1.svc.cluster.local:7050
    - name: ORG
      value: netop1
    - name: SYS_CHANNEL
      value: netop1-channel
    - name: TEST_CHANNEL
      value: mychannel
    workingDir: /etc/hyperledger/cli/artifacts
    volumeMounts:
    - mountPath: /host/var/run
      name: docker-sock
    - mountPath: /etc/hyperledger/cli/artifacts
      name: artifacts
    - mountPath: /opt/gopath/src/github.com/chaincode
      name: chaincode
    - mountPath: /etc/hyperledger/cli/crypto
      name: crypto
  volumes:
  - name: docker-sock
    hostPath:
      path: /var/run
      type: Directory
  - name: artifacts
    persistentVolumeClaim:
      claimName: artifacts-cli
  - name: crypto
    persistentVolumeClaim:
      claimName: crypto-cli
  - name: chaincode
    persistentVolumeClaim:
      claimName: chaincode-cli
