
kind: Service
apiVersion: v1
metadata:
  name: orderer
  namespace: netop1
  labels:
    app: orderer
spec:
  selector:
    app: orderer
  ports:
  - port: 7050
    name: server
  # headless service for orderer StatefulSet
  clusterIP: None
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: orderer
  namespace: netop1
spec:
  selector:
    matchLabels:
      app: orderer
  serviceName: orderer
  replicas: 3
  template:
    metadata:
      labels:
        app: orderer
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: orderer
        imagePullPolicy: Always
        image: hyperledger/fabric-orderer:1.4.3
        resources:
          requests:
            memory: 500Mi
            cpu: 100m
        ports:
        - containerPort: 7050
          name: server
        command:
        - orderer
        env:
        - name: FABRIC_LOGGING_SPEC
          value: INFO
        - name: ORDERER_GENERAL_LISTENADDRESS
          value: 0.0.0.0
        - name: ORDERER_GENERAL_GENESISMETHOD
          value: file
        - name: ORDERER_FILELEDGER_LOCATION
          value: /var/hyperledger/orderer/store/data
        - name: ORDERER_GENERAL_GENESISFILE
          value: /var/hyperledger/orderer/store/genesis.block
        - name: ORDERER_GENERAL_LOCALMSPID
          value: netop1OrdererMSP
        - name: ORDERER_GENERAL_LOCALMSPDIR
          value: /var/hyperledger/orderer/store/crypto/msp
        - name: ORDERER_GENERAL_TLS_ENABLED
          value: "true"
        - name: ORDERER_GENERAL_TLS_PRIVATEKEY
          value: /var/hyperledger/orderer/store/crypto/tls/server.key
        - name: ORDERER_GENERAL_TLS_CERTIFICATE
          value: /var/hyperledger/orderer/store/crypto/tls/server.crt
        - name: ORDERER_GENERAL_TLS_ROOTCAS
          value: /var/hyperledger/orderer/store/crypto/tls/ca.crt
        - name: ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE
          value: /var/hyperledger/orderer/store/crypto/tls/server.crt
        - name: ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY
          value: /var/hyperledger/orderer/store/crypto/tls/server.key
        - name: ORDERER_GENERAL_CLUSTER_ROOTCAS
          value: /var/hyperledger/orderer/store/crypto/tls/server.crt
        - name: GODEBUG
          value: netdns=go
        volumeMounts:
        - mountPath: /var/hyperledger/orderer/store
          name: data
        workingDir: /opt/gopath/src/github.com/hyperledger/fabric/orderer
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes:
      - ReadWriteOnce
      storageClassName: "netop1-orderer-data-class"
      resources:
        requests:
          storage: 500Mi
