
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: netop1-tool-data-class
provisioner: kubernetes.io/no-provisioner
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: data-netop1-tool
  labels:
    app: data-tool
    org: netop1
spec:
  capacity:
    storage: 100Mi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: netop1-tool-data-class
  hostPath:
    path: /Users/yxu/work/hyperledger/fabric-operation/netop1.com/tool
    type: Directory
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: data-tool
  namespace: netop1
spec:
  storageClassName: netop1-tool-data-class
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  selector:
    matchLabels:
      app: data-tool
      org: netop1
