version: '2'

networks:
  netop1:

services:

  orderer-0.netop1.com:
    container_name: orderer-0.netop1.com
    image: hyperledger/fabric-orderer
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=netop1OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
        - /Users/yxu/work/hyperledger/fabric-operation/netop1.com/tool/etcdraft-genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - /Users/yxu/work/hyperledger/fabric-operation/netop1.com/orderers/orderer-0/crypto/msp/:/var/hyperledger/orderer/msp
        - /Users/yxu/work/hyperledger/fabric-operation/netop1.com/orderers/orderer-0/crypto/tls/:/var/hyperledger/orderer/tls
        - orderer-0.netop1.com:/var/hyperledger/production/orderer
    ports:
      - 7050:7050
    networks:
      - netop1

  orderer-1.netop1.com:
    container_name: orderer-1.netop1.com
    image: hyperledger/fabric-orderer
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=netop1OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
        - /Users/yxu/work/hyperledger/fabric-operation/netop1.com/tool/etcdraft-genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - /Users/yxu/work/hyperledger/fabric-operation/netop1.com/orderers/orderer-1/crypto/msp/:/var/hyperledger/orderer/msp
        - /Users/yxu/work/hyperledger/fabric-operation/netop1.com/orderers/orderer-1/crypto/tls/:/var/hyperledger/orderer/tls
        - orderer-1.netop1.com:/var/hyperledger/production/orderer
    ports:
      - 7060:7050
    networks:
      - netop1

  orderer-2.netop1.com:
    container_name: orderer-2.netop1.com
    image: hyperledger/fabric-orderer
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=netop1OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
        - /Users/yxu/work/hyperledger/fabric-operation/netop1.com/tool/etcdraft-genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - /Users/yxu/work/hyperledger/fabric-operation/netop1.com/orderers/orderer-2/crypto/msp/:/var/hyperledger/orderer/msp
        - /Users/yxu/work/hyperledger/fabric-operation/netop1.com/orderers/orderer-2/crypto/tls/:/var/hyperledger/orderer/tls
        - orderer-2.netop1.com:/var/hyperledger/production/orderer
    ports:
      - 7070:7050
    networks:
      - netop1

  peer-0.netop1.com:
    container_name: peer-0.netop1.com
    image: hyperledger/fabric-peer
    environment:
      - CORE_PEER_ID=peer-0.netop1.com
      - CORE_PEER_ADDRESS=peer-0.netop1.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer-0.netop1.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer-1.netop1.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer-0.netop1.com:7051
      - CORE_PEER_LOCALMSPID=netop1MSP
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      # the following setting starts chaincode containers on the same
      # bridge network as the peers
      # https://docs.docker.com/compose/networking/
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=docker_netop1
      - FABRIC_LOGGING_SPEC=INFO
      #- FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt

      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb-0:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=

    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    volumes:
        - /var/run/:/host/var/run/
        - /Users/yxu/work/hyperledger/fabric-operation/netop1.com/peers/peer-0/crypto/msp/:/etc/hyperledger/fabric/msp
        - /Users/yxu/work/hyperledger/fabric-operation/netop1.com/peers/peer-0/crypto/tls/:/etc/hyperledger/fabric/tls
        - peer-0.netop1.com:/var/hyperledger/production
    ports:
      - 7051:7051
    networks:
      - netop1

  couchdb-0:
    container_name: couchdb-0
    image: hyperledger/fabric-couchdb
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
    # Comment/Uncomment the port mapping if you want to hide/expose the CouchDB service,
    # for example map it to utilize Fauxton User Interface in dev environments.
    ports:
      - 7056:5984
    networks:
      - netop1

  peer-1.netop1.com:
    container_name: peer-1.netop1.com
    image: hyperledger/fabric-peer
    environment:
      - CORE_PEER_ID=peer-1.netop1.com
      - CORE_PEER_ADDRESS=peer-1.netop1.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer-1.netop1.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer-0.netop1.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer-1.netop1.com:7051
      - CORE_PEER_LOCALMSPID=netop1MSP
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      # the following setting starts chaincode containers on the same
      # bridge network as the peers
      # https://docs.docker.com/compose/networking/
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=docker_netop1
      - FABRIC_LOGGING_SPEC=INFO
      #- FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt

      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb-1:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=

    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    volumes:
        - /var/run/:/host/var/run/
        - /Users/yxu/work/hyperledger/fabric-operation/netop1.com/peers/peer-1/crypto/msp/:/etc/hyperledger/fabric/msp
        - /Users/yxu/work/hyperledger/fabric-operation/netop1.com/peers/peer-1/crypto/tls/:/etc/hyperledger/fabric/tls
        - peer-1.netop1.com:/var/hyperledger/production
    ports:
      - 7061:7051
    networks:
      - netop1

  couchdb-1:
    container_name: couchdb-1
    image: hyperledger/fabric-couchdb
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
    # Comment/Uncomment the port mapping if you want to hide/expose the CouchDB service,
    # for example map it to utilize Fauxton User Interface in dev environments.
    ports:
      - 7066:5984
    networks:
      - netop1

  cli:
    container_name: cli
    image: hyperledger/fabric-tools
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      #- FABRIC_LOGGING_SPEC=DEBUG
      - FABRIC_LOGGING_SPEC=INFO
      - ORG=netop1
      - SYS_CHANNEL=netop1-channel
      - TEST_CHANNEL=mychannel
      - ORDERER_TYPE=etcdraft
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer-0.netop1.com:7051
      - CORE_PEER_LOCALMSPID=netop1MSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/cli/crypto/peer-0/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/cli/crypto/peer-0/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/cli/crypto/peer-0/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/cli/crypto/Admin@netop1.com/msp
      - ORDERER_CA=/etc/hyperledger/cli/crypto/orderer-0/msp/tlscacerts/tlsca.netop1.com-cert.pem
      - ORDERER_URL=orderer-0.netop1.com:7050
      - FABRIC_ORG=netop1.com
    working_dir: /etc/hyperledger/cli
    command: /bin/bash
    volumes:
      - /var/run/:/host/var/run/
      - /Users/yxu/work/hyperledger/fabric-operation/netop1.com/cli/:/etc/hyperledger/cli/
      - /Users/yxu/work/hyperledger/fabric-operation/netop1.com/cli/chaincode/:/opt/gopath/src/github.com/chaincode:cached
    networks:
      - netop1
    depends_on:
      - peer-0.netop1.com
      - peer-1.netop1.com

volumes:
  orderer-0.netop1.com:
  orderer-1.netop1.com:
  orderer-2.netop1.com:
  peer-0.netop1.com:
  peer-1.netop1.com:
